### PR TITLE
View course info

### PR DESCRIPTION
**Pull request by RHornberger20**

### CODE REVIEW

**Comment by Pirundy** [comment]
@Jake-Derrick can you take a look at this pull request I'm getting some issues with courses.test.js in routes after merging

**Comment by Jake-Derrick** [comment]
> @Jake-Derrick can you take a look at this pull request I'm getting some issues with courses.test.js in routes after merging

Looks like findAll needed a mock return value. I added it to the beforeEach in courses.test.ts

**Review by Jake-Derrick — APPROVED** [review]
This looks good to me! The api returned 0 courses for me, were you able to get courses returned?

**Comment by Pirundy** [comment]
> This looks good to me! The api returned 0 courses for me, were you able to get courses returned?

Yep, I was able to grab courses from the database they just need to have a semester and course semester in order to load up. Thanks for the help!

courses

**Comment by JustinChipman** [comment]
Looks good to me

**Review by JustinChipman — APPROVED** [review]
looks good to me

**Pull request merged**
