### PR TITLE
Terms

### PR DESCRIPTION
**Pull request by ColeLindner**
Have not completed editing the name just doing an initial merge so that others are allowed to used the page for their work.

### CODE REVIEW

**Review by Pirundy — APPROVED** [review]
Code looks great good job!

**Comment by ckemp1** [comment]
I'm not sure if this is intentional, but there is no manage page in navigation.js

**Comment by ColeLindner** [comment]
> I'm not sure if this is intentional, but there is no manage page in navigation.js

I don't know why that would happen I didn't touch manage and when I run it I can still see manage. 
image
(if that showed the image.

**Review by ckemp1 — APPROVED** [review]
I'm dumb, it just wasn't showing the manage in the preview since its a line above, but its there in that branch. Anyways, looks good!

**Pull request merged**
